'use strict';

var rulesConfiguration = require('./rules/utils/rulesConfiguration.js');

rulesConfiguration.addRule('angularelement', 0);
rulesConfiguration.addRule('component-limit', [0, 1]);
rulesConfiguration.addRule('controller-as', 0);
rulesConfiguration.addRule('controller-as-route', 0);
rulesConfiguration.addRule('controller-as-vm', 0);
rulesConfiguration.addRule('controller-name', 0);
rulesConfiguration.addRule('deferred', 0);
rulesConfiguration.addRule('definedundefined', 0);
rulesConfiguration.addRule('di', [0, 'function']);
rulesConfiguration.addRule('di-order', 0);
rulesConfiguration.addRule('di-unused', 0);
rulesConfiguration.addRule('directive-name', 0);
rulesConfiguration.addRule('directive-restrict', 0);
rulesConfiguration.addRule('document-service', 0);
rulesConfiguration.addRule('dumb-inject', 0);
rulesConfiguration.addRule('empty-controller', 0);
rulesConfiguration.addRule('file-name', 0);
rulesConfiguration.addRule('filter-name', 0);
rulesConfiguration.addRule('foreach', 0);
rulesConfiguration.addRule('function-type', 0);
rulesConfiguration.addRule('interval-service', 0);
rulesConfiguration.addRule('json-functions', 0);
rulesConfiguration.addRule('log', 0);
rulesConfiguration.addRule('module-dependency-order', [0, {grouped: false, prefix: null}]);
rulesConfiguration.addRule('module-getter', 0);
rulesConfiguration.addRule('module-name', 0);
rulesConfiguration.addRule('module-setter', 0);
rulesConfiguration.addRule('no-angular-mock', 0);
rulesConfiguration.addRule('no-controller', 0);
rulesConfiguration.addRule('no-cookiestore', 0);
rulesConfiguration.addRule('no-directive-replace', 0);
rulesConfiguration.addRule('no-http-callback', 0);
rulesConfiguration.addRule('no-inline-template', [0, {allowSimple: true}]);
rulesConfiguration.addRule('no-jquery-angularelement', 0);
rulesConfiguration.addRule('no-private-call', 0);
rulesConfiguration.addRule('no-run-logic', 0);
rulesConfiguration.addRule('no-services', [0, ['$http', '$resource', 'Restangular', '$q', '$filter']]);
rulesConfiguration.addRule('no-service-method', 0);
rulesConfiguration.addRule('on-watch', 0);
rulesConfiguration.addRule('one-dependency-per-line', 0);
rulesConfiguration.addRule('rest-service', 0);
rulesConfiguration.addRule('service-name', 0);
rulesConfiguration.addRule('timeout-service', 0);
rulesConfiguration.addRule('typecheck-array', 0);
rulesConfiguration.addRule('typecheck-date', 0);
rulesConfiguration.addRule('typecheck-function', 0);
rulesConfiguration.addRule('typecheck-number', 0);
rulesConfiguration.addRule('typecheck-object', 0);
rulesConfiguration.addRule('typecheck-string', 0);
rulesConfiguration.addRule('watchers-execution', [0, '$digest']);
rulesConfiguration.addRule('window-service', 0);

module.exports = rulesConfiguration.moduleExports();
