on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v4
      with:
        version: 11.12.0
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm test
